version: "3"

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER_NAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_USER_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${GRAFANA_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ${DATA_DIR}/influxdb/data:/var/lib/influxdb2
      - ${DATA_DIR}/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    networks:
      - mtig_network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ${DATA_DIR}/mosquitto/config:/mosquitto/config
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/certs:/mosquitto/certs
    restart: unless-stopped
    ports:
      - 1883:1883
    networks:
      - mtig_network

  telegraf:
    image: telegraf:1.26-alpine
    container_name: telegraf
    user: telegraf
    environment:
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_URL: ${MQTT_URL}
      GRAFANA_ORG_NAME: ${GRAFANA_ORG_NAME}
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      DTU_SERIAL: ${DTU_SERIAL}
      DTU_BASE_TOPIC: ${DTU_BASE_TOPIC}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      OPEN_WEATHER_CITY_ID: ${OPEN_WEATHER_CITY_ID}
    volumes:
      - ${DATA_DIR}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - mtig_network

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ${DATA_DIR}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${DATA_DIR}/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ${DATA_DIR}/grafana/dashboards:/dashboards
      - ${DATA_DIR}/grafana/var:/var/lib/grafana
    restart: unless-stopped
    networks:
      - mtig_network

networks:
  mtig_network:
    driver: bridge
