apiVersion: 1

datasources:
  - name: InfluxDB_Telegraf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: [ORGANIZATION]
      defaultBucket: telegraf
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "token [TOKEN]"
      token: "[TOKEN]"
  - name: Sun and Moon
    type: fetzerch-sunandmoon-datasource
    typeName: Sun and Moon
    typeLogoUrl: public/plugins/fetzerch-sunandmoon-datasource/img/logo.png
    access: proxy
    jsonData:
      latitude: [LATITUDE]
      longitude: [LONGITUDE]
